## Pandas
### Task01：预备知识

# 一、Python基础
## 1.列表推导式与条件赋值
例1：生成一个数字序列




In [52]:
L = []
def my_func(x):
    return 2*x;
for i in range(5):
    L.append(my_func(i))
L

[0, 2, 4, 6, 8]

例2：
简化写法[* for i in *]



第一个 * 为映射函数，其输入为后面 i 指代的内容；第二个 * 表示迭代的对象

In [53]:
#列表推导式简化写法
[my_func(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [54]:
[2*i for i in range(5)]

[0, 2, 4, 6, 8]

In [55]:
#前开后闭的集合(0,k-1]
for i in range(6):
  print(i)

0
1
2
3
4
5


例3：列表表达式多层嵌套

In [56]:
[m+'_'+n for m in ['a','b'] for n in ['c', 'd']]

['a_c', 'a_d', 'b_c', 'b_d']

例4：if条件选择的条件赋值

In [57]:
# value = a if condition else b
value = 'cat' if 2>1 else 'dog'
value

'cat'

In [58]:
#等价写法
a ,b = 'cat','dog'
condition =2>1 #此时为 true
if condition:
  value = a
else:
  value = b
value

'cat'

In [59]:
#示例：阶段列表张超过5的元素（即超过5的用5代替，小于5的保留原值）
L=[1,2,3,4,5,6,7,8,6,3]
[i if i<=5 else 5 for i in L]

[1, 2, 3, 4, 5, 5, 5, 5, 5, 3]

## 2.匿名函数与map方法


例1：一些函数具有清晰简单的映射关系，例如上述 my_func 函数，这时可以用匿名函数简洁表示

In [60]:
my_func = lambda x:2*x
my_func(3)

multi_para_func = lambda a,b:a+b
multi_para_func(1,2)
# 这种用法违背了“匿名”的含义，一般在无需多处调用时使用，用户不需要关心函数的名字，只需要明白这种映射关系即可

3

In [61]:
#列表推导式的匿名函数映射
[(lambda x:2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [62]:
#列表推导式的匿名函数映射,可以用Python中的map函数实现，返回的map对象通过list转为列表
list(map(lambda x: 2*x, range(5)))

[0, 2, 4, 6, 8]

In [63]:
#有多个输入值的函数映射，可以通过追加迭代对象实现
list(map(lambda x, y: str(x) + '_' + y, range(5), list('abcde')))

['0_a', '1_b', '2_c', '3_d', '4_e']

In [64]:
list('abcde')

['a', 'b', 'c', 'd', 'e']

## 3.zip对象与enumerate方法

### 3.1 zip函数
能把多个可迭代对象打包成一个元组构成的可迭代对象，它返回了一个zip对象，通过tuple，list可以得到相应的打包结果。

In [65]:
L1,L2,L3 = list('abc'),list('def'),list('hij')
list(zip(L1,L2,L3))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [66]:
L1,L2,L3 = list('my'),list('gg'),list('bb')
tuple(zip(L1,L2,L3))

(('m', 'g', 'b'), ('y', 'g', 'b'))

In [67]:
#通常在循环迭代时用zip函数
for i,j,k in zip(L1,L2,L3):
  print(i,j,k)

m g b
y g b


### 3.2 enumerate
特殊的打包，可以在迭代时绑定迭代元素的遍历序号

In [68]:
L=list('abcd')
for index,value in enumerate(L):
  print(index,value)

0 a
1 b
2 c
3 d


In [69]:
#用zip函数实现上述功能
for index,value in zip(range(len(L)), L):
  print(index,value)

0 a
1 b
2 c
3 d


In [70]:
len(L)

4

注1：当需要对两个列表建立字典映射时，可以利用zip对象

In [71]:
dict(zip(L1,L2))

{'m': 'g', 'y': 'g'}

注2：有压缩函数，Python提供*操作符和zip联合使用可以进行解压操作

In [72]:
zipped=list(zip(L1,L2,L3))
zipped

[('m', 'g', 'b'), ('y', 'g', 'b')]

In [73]:
list(zip(*zipped))  #三个元组分别对应原来的列表

[('m', 'y'), ('g', 'g'), ('b', 'b')]

# 二、Numpy基础

## 1.np数组的构造

### 1.1 一般方法：用array构造

In [74]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

### 1.2 特殊数组的生成方式

#### （1）等差序列：np.linspace ， np.arange

In [75]:
np.linspace(1,5,11)  # 起始、终止（包含）、样本数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [76]:
np.arange(1,5,2)   #起始、终止（不包含）、步长

array([1, 3])

#### （2）特殊矩阵：zeros , eye , full

In [77]:
np.zeros((2,3))  #传入元组表示各维度大小
# array[[a1,a2,a3],[b1,b2,b3]]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.eye(3)  # 3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.eye(3,k=1) #  偏移主对角线1个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [80]:
np.full((2,3),10)  # 元组传入大小，10表示填充数值

np.full((2,3),[1,2,3])  # 通过传入列表填充每列的值

array([[1, 2, 3],
       [1, 2, 3]])

#### （3）随机矩阵： np.random


rand：0-1均匀分布的随机数组；
randn：标准正态的随机数组；
randint：随机整数组；
choice：随机列表抽样

In [81]:
np.random.rand(3) # 生成服从0-1均匀分布的三个随机数

array([0.2226905 , 0.89499621, 0.64974698])

In [82]:
np.random.rand(3, 3) # 注意这里传入的不是元组，每个维度大小分开输入

array([[0.49771792, 0.8882868 , 0.77706453],
       [0.60076321, 0.74206795, 0.73279941],
       [0.1955562 , 0.91328742, 0.41339996]])

In [83]:
# 服从(a,b)区间上的均匀分布函数
a, b = 5, 15
(b - a) * np.random.rand(3) + a

array([12.40632334,  8.05871528,  8.13193347])

In [84]:
# randn 生成 N(0,I) 的标准正态分布
np.random.randn(3)

np.random.randn(2, 2)

array([[-0.26594575,  1.20779744],
       [-1.70121724,  0.54311168]])

In [85]:
# 生成服从方差为 σ2 均值为 μ 的一元正态分布
sigma, mu = 2.5, 3
mu + np.random.randn(3) * sigma

array([-0.38387887,  1.98265548,  8.32262062])

In [86]:
# randint 可以指定生成随机整数的最小值最大值（不包含）和维度大小
low, high, size = 5, 15, (2,2) # 生成5到14的随机整数
np.random.randint(low, high, size)

array([[ 8, 13],
       [13, 13]])

In [87]:
# choice 可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率时为均匀采样，默认抽取方式为有放回抽样
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])

np.random.choice(my_list, (3,3))

array([['a', 'a', 'a'],
       ['a', 'd', 'a'],
       ['a', 'b', 'd']], dtype='<U1')

#### （4）当返回的元素个数与原列表相同时，等价于使用 permutation 函数，即打散原列表

In [88]:
np.random.permutation(my_list)

array(['c', 'a', 'b', 'd'], dtype='<U1')

####（5）随机种子：能够固定随机数的输出结果

In [89]:
 np.random.seed(0)
 np.random.rand()

0.5488135039273248

In [90]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

## 2.np数组的变形与合并

### 2.1 转置：T

In [91]:
 np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### 2.2 合并操作：r_ , c_
# 对二维数组，r_和c_分别表示上下合并和左右合并

In [92]:
# 上下合并
np.r_[np.zeros((2,3)),np.zeros((2,3))]
# 左右合并
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

注意：一维数组和二维数组进行合并时，应当把其视作列向量，在长度匹配的情况下只能够使用左右合并的 c_ 操作

In [93]:
try:
  np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
  Err_Msg = e

In [94]:
 Err_Msg

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

In [95]:
np.r_[np.array([0,0]),np.zeros(2)]

array([0., 0., 0., 0.])

In [96]:
np.zeros(2)

array([0., 0.])

In [97]:
np.c_[np.array([0,0]),np.zeros((2,3))]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### 2.3 维度变换：reshape
把原数组按照新的维度重新排列。在使用时有两种模式，分别为C模式和F模式，分别以逐行和逐列的顺序进行填充读取

In [99]:
 target = np.arange(8).reshape(2,4)
 target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [100]:
target.reshape((4,2), order='C') # 按照行读取和填充

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [101]:
target.reshape((4,2), order='F') # 按照列读取和填充

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

注意：特别地，由于被调用数组的大小是确定的， reshape 允许有一个维度存在空缺，此时只需填充-1即可

In [102]:
target.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [103]:
# 将n*1大小的数组转为1维数组的操作：
target = np.ones((3,1))
target

array([[1.],
       [1.],
       [1.]])

In [104]:
target.reshape(-1)

array([1., 1., 1.])

## 3. np数组的切片与索引
数组的切片模式支持使用 slice 类型的 start:end:step 切片，还可以直接传入列表指定某个维度的索引进行切片

In [105]:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
target[:-1, [0,2]]

array([[0, 2],
       [3, 5]])

当数组维度为1时，可以直接进行布尔索引，无需np.ix_

In [107]:
new = target.reshape(-1)
new[new%2==0]

array([0, 2, 4, 6, 8])

## 4. 常用函数

In [108]:
#以一维数组为例

### 4.1 where
条件函数，可以指定满足条件与不满足条件位置对应的填充值

In [109]:
 a = np.array([-1,1,-1,0])
np.where(a>0, a, 5) # 对应位置为True时填充a对应元素，否则填充5

array([5, 1, 5, 5])

### 4.2 nonzero，argmax，argmin
这三个函数返回的都是索引， nonzero 返回非零数的索引， argmax, argmin 分别返回最大和最小数的索引

In [110]:
 a = np.array([-2,-5,0,1,3,-1])
 np.nonzero(a)

(array([0, 1, 3, 4, 5]),)

In [111]:
a.argmax()

4

In [112]:
a.argmin()

1

### 4.3 any，all
any：指当序列至少 存在一个 True 或非零元素时返回 True ，否则返回 False


all：指当序列元素 全为 True 或非零元素时返回 True ，否则返回 False

In [113]:
a = np.array([0,1])

In [114]:
a.any()

True

In [115]:
a.all()

False

### 4.4 cumprod,cumsum,diff
cumprod, cumsum 分别表示累乘和累加函数，返回同长度的数组


diff 表示和前一个元素做差，由于第一个元素为缺失值，因此在默认参数情况下，返回长度是原数组减1

In [116]:
a = np.array([1,2,3])
a.cumprod()

array([1, 2, 6])

In [117]:
a.cumsum()

array([1, 3, 6])

In [118]:
np.diff(a)

array([1, 1])

### 4.5 统计函数
常用的统计函数包括 max, min, mean, median, std, var, sum, quantile ，其中分位数计算是全局方法，因此不能通过 array.quantile 的方法调用

In [119]:
target = np.arange(5)
target

array([0, 1, 2, 3, 4])

In [120]:
target.max()

4

In [121]:
np.quantile(target, 0.5) # 0.5分位数

2.0

注：对于含有缺失值的数组，它们返回的结果也是缺失值，如果需要略过缺失值，必须使用 nan* 类型的函数，上述的几个统计函数都有对应的 nan* 函数

In [122]:
target = np.array([1, 2, np.nan])
target

target.max()

np.nanmax(target)

np.nanquantile(target, 0.5)

1.5

协方差：cov

In [123]:
target1 = np.array([1,3,5,9])
target2 = np.array([1,5,3,-9])
np.cov(target1, target2)

array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

相关系数：corrcoef

In [124]:
np.corrcoef(target1, target2)

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

说明：二维 Numpy 数组中统计函数的 axis 参数，它能够进行某一个维度下的统计特征计算，当 axis=0 时结果为列的统计指标，当 axis=1 时结果为行的统计指标

In [125]:
target = np.arange(1,10).reshape(3,-1)
target
target.sum(0) # array([12, 15, 18])
target.sum(1) # array([ 6, 15, 24])

array([ 6, 15, 24])

## 5. 广播机制
用于处理两个不同维度数组之间的操作，这里只讨论不超过两维的数组广播机制

### 5.1 标量和数组的操作
当一个标量和数组进行运算时，标量会自动把大小扩充为数组大小，之后进行逐元素操作

In [126]:
res = 3 * np.ones((2,2)) + 1
res

array([[4., 4.],
       [4., 4.]])

In [127]:
res = 1 / res
res 

array([[0.25, 0.25],
       [0.25, 0.25]])

### 5.2 二维数组之间的操作
当两个数组维度完全一致时，使用对应元素的操作，否则会报错，除非其中的某个数组的维度是 m×1 或者 1×n ，那么会扩充其具有 1 的维度为另一个数组对应维度的大小

例如， 1×2 数组和 3×2 数组做逐元素运算时会把第一个数组扩充为 3×2 ，扩充时的对应数值进行赋值。但是，需要注意的是，如果第一个数组的维度是 1×3 ，那么由于在第二维上的大小不匹配且不为 1 ，此时报错

In [128]:
res = np.ones((3,2))
res

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [129]:
res * np.array([[2,3]]) # 扩充第一维度为3

array([[2., 3.],
       [2., 3.],
       [2., 3.]])

In [130]:
res * np.array([[2],[3],[4]]) # 扩充第二维度为2

array([[2., 2.],
       [3., 3.],
       [4., 4.]])

In [131]:
res * np.array([[2]]) # 等价于两次扩充

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

### 5.3 一维数组与二维数组的操作
当一维数组 Ak 与二维数组 Bm,n 操作时，等价于把一维数组视作 A1,k 的二维数组，使用的广播法则与【b】中一致，当 k!=n 且 k,n 都不是 1 时报错

In [132]:
np.ones(3) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [133]:
np.ones(3) + np.ones((2,1))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [134]:
np.ones(1) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

## 6. 向量与矩阵的计算

### 6.1 向量内积 
dot a·b=∑aibi

In [136]:
a = np.array([1,2,3])
b = np.array([1,3,5])
a.dot(b)

22

### 6.2 向量范数和矩阵范数
 np.linalg.norm

在矩阵范数的计算中，最重要的是 ord 参数

### 6.3 矩阵乘法
`@`

$$[A_{m*p}B_{p*n}]_{ij}=\sum^p_{k=1}A_{ik}B_{kj}$$


## 练习

###Ex1：利用列表推导式写矩阵乘法

In [137]:
import numpy as np
# (* for i in *)
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
# (res[i][j] = M1[i][k] * M2[k][j])  )
res = [[sum(M1[i][k] * M2[k][j] for k in range(M1.shape[1])) for j in range(M2.shape[1])] for i in range(M1.shape[0])]


In [138]:
((M1@M2 - res) < 1e-15).all()

True